### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by ushukkla**
Doing this course

### CODE REVIEW

**Comment by elija33** [comment]
Yes I am. what about you?

**Comment by ychaikin** [comment]
Not sure what the point of this PR is. Some formatting?

**Comment by elija33** [comment]
Hello professor, first thank you for your time for making the tutorial on
coursera  for someone like me who can not afford college. I am taking
Single Page Web Applications with AngularJs  on coursera  but I do not know
if I am missing something on previous courses, I am not getting the full
understanding of AngularJS. do you have any suggestions for me pls.

**Comment by ychaikin** [comment]
This isn't a forum for discussions like this. This is for issues with code, etc. 
If you are having hard time understanding that course, I suggest the prerequisite course, which is also mine on Coursera: https://www.coursera.org/learn/html-css-javascript-for-web-developers

**Comment by elija33** [comment]
Thank You

**Comment by elija33** [comment]
I took Html, Css and Js on coursera from University of Michigan which I
have been build static site but I want to know dynamic site.

**Pull request closed without merging**
