### PR TITLE
Update controller names

### PR DESCRIPTION
**Pull request by arku**
Rename controller names to stay consistent with Step 8

### CODE REVIEW

**Comment by ychaikin** [comment]
@arun1595 You're changing the names why?

**Comment by arku** [comment]
In the 8th step of the [steps](https://github.com/jhu-ep-coursera/fullstack-course5/blob/master/assignments/assignment2/Assignment-2.md#steps) section, the controller names specified are `ToBuyShoppingController` and `AlreadyBoughtShoppingController` but in the 9th step, the names are wrongly mentioned as `ToBuyController` and `AlreadyBoughtController`.

To make the steps consistent, the PR changes the controller names in the 9th step.

Let me know if you need any other clarifications.

**Comment by ychaikin** [comment]
@arun1595 Thanks. I just fixed that the other way around. Made the names shorter everywhere.

**Comment by arku** [comment]
@ychaikin Great! I first submitted a PR making the controller names shorter but then closed it. LOL

**Comment by ychaikin** [comment]
@arun1595 :-) Thanks for helping out!

**Pull request closed without merging**
